### ISSUE TITLE
一部環境においてアプリのアンインストールが不可能になる

### ISSUE THREAD

**Issue by Awayume** [saradabar/Touch2_Custom_Tool#2]
アバスト モバイルセキュリティなどのセキュリティアプリをインストールしている状態だと、自動的にアカウントが登録され、
設定→アカウントからの(セキュリティアプリのアカウントの)削除がブロックされます。
この状態では、そのセキュリティアプリをアンインストールしないと解除できません。
それに加え、DeviceOwnerが解除される前にアンストブロックが有効化されていると、セキュリティアプリをアンインストール
することが不可能なため、セキュリティアプリのアカウント削除が不可能になります。
アカウントが設定されているとDeviceOwnerがセットできないため、アンストブロックを解除することが不可能になり、
初期化を余儀なくされます。

**Comment by saradabar** [comment]
報告ありがとうございます。
指摘された問題については速やかに調査をし、修正するようにします。
修正が完了次第報告します。

**Comment by saradabar** [comment]
おはようございます。
問題が解決したことをお知らせします。

**Comment by Awayume** [comment]
ありがとうございました。
